formatting

diff --git a/.github/workflows/ts-formatting.yml b/.github/workflows/ts-formatting.yml
--- a/.github/workflows/ts-formatting.yml
+++ b/.github/workflows/ts-formatting.yml
@@ -13,40 +13,38 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 16
+      - uses: actions/checkout@v3
 
-    - uses: actions/setup-node@v3
-      with:
-        node-version: 16
-    - uses: actions/checkout@v3
+      - name: Check
+        run: npx prettier --check ./**/*.ts
 
-    - name: Check
-      run: npx prettier --check ./**/*.ts
-
-    - name: Fail fast?!
-      if: failure()
-      run: |
-        echo "Some files failed the formatting checks!"; exit 1
+      - name: Fail fast?!
+        if: failure()
+        run: |
+          echo "Some files failed the formatting checks!"; exit 1
 
   lint:
     name: TS Lint check
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 16
 
-    - uses: actions/setup-node@v3
-      with:
-        node-version: 16
-  
-    - uses: 0xADE1A1DE/AssemblyLine@dev
+      - uses: 0xADE1A1DE/AssemblyLine@dev
 
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Install dependencies
-      run: npm install
+      - name: Install dependencies
+        run: npm install
 
-    - name: Check Lint
-      run: npm  run lint
+      - name: Check Lint
+        run: npm  run lint
 
-    - name: Fail fast?!
-      if: failure()
-      run: |
-        echo "Some files failed the linting checks!"; exit 1
+      - name: Fail fast?!
+        if: failure()
+        run: |
+          echo "Some files failed the linting checks!"; exit 1
